#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-mkdocs_htmlproofer_plugin
Version  : 0.12.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/c0/e3/58f7cc37e505788bac0cb811c0a3573ba612688bfbd5606cafb476bdbc50/mkdocs-htmlproofer-plugin-0.12.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/c0/e3/58f7cc37e505788bac0cb811c0a3573ba612688bfbd5606cafb476bdbc50/mkdocs-htmlproofer-plugin-0.12.0.tar.gz
Summary  : A MkDocs plugin that validates URL in rendered HTML files
Group    : Development/Tools
License  : MIT
Requires: pypi-mkdocs_htmlproofer_plugin-python = %{version}-%{release}
Requires: pypi-mkdocs_htmlproofer_plugin-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# mkdocs-htmlproofer-plugin [![PyPI - Version](https://img.shields.io/pypi/v/mkdocs-htmlproofer-plugin.svg)](https://pypi.org/project/mkdocs-htmlproofer-plugin)

%package python
Summary: python components for the pypi-mkdocs_htmlproofer_plugin package.
Group: Default
Requires: pypi-mkdocs_htmlproofer_plugin-python3 = %{version}-%{release}

%description python
python components for the pypi-mkdocs_htmlproofer_plugin package.


%package python3
Summary: python3 components for the pypi-mkdocs_htmlproofer_plugin package.
Group: Default
Requires: python3-core
Provides: pypi(mkdocs_htmlproofer_plugin)
Requires: pypi(beautifulsoup4)
Requires: pypi(markdown)
Requires: pypi(mkdocs)
Requires: pypi(requests)

%description python3
python3 components for the pypi-mkdocs_htmlproofer_plugin package.


%prep
%setup -q -n mkdocs-htmlproofer-plugin-0.12.0
cd %{_builddir}/mkdocs-htmlproofer-plugin-0.12.0
pushd ..
cp -a mkdocs-htmlproofer-plugin-0.12.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1681502179
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
